package com.idea.ddm.access;
import static org.junit.jupiter.api.Assertions.*;
import com.idea.ddm.iam.IamIntegrationFixtures;
import java.net.http.HttpResponse;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class CustomRoleAtomicityTest {
    final CustomRoleQualificationFixture f=new CustomRoleQualificationFixture();
    @BeforeAll void start()throws Exception{f.start();}@AfterAll void stop(){f.close();}
    @Test void requiredOutcomeEnvelopeDecisionAuditAndDeferredCommitFailuresRollBackActivation()throws Exception{
        var actor=f.rows.identity(IamIntegrationFixtures.Persona.PRA);f.http.withSignedInClient(actor,(client,ctx)->{f.delegate(actor);var candidate=f.prepare(client);var id=candidate.path("candidateId").asString();
            for(var table:List.of("access_policy_owner_outcome","role_definition_owner_operation","role_definition_authorization_evidence","audit_evidence")){
                var input=f.activation();var op=input.get("operationId");f.sql("CREATE FUNCTION suppress_custom() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END $$");f.sql("CREATE TRIGGER suppress_custom BEFORE INSERT ON "+table+" FOR EACH ROW EXECUTE FUNCTION suppress_custom()");try{assertEquals(503,f.post(client,f.activatePath(candidate),input).statusCode());}finally{f.sql("DROP TRIGGER suppress_custom ON "+table);f.sql("DROP FUNCTION suppress_custom()");}absent(op);assertEquals(1,f.count("SELECT version FROM identity_role_candidate WHERE candidate_id='"+id+"'"));assertEquals(0,f.count("SELECT count(*) FROM identity_role_version_profile WHERE definition_id='"+candidate.path("definitionId").asString()+"'"));
            }
            f.sql("CREATE FUNCTION reject_custom_commit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Synthetic deferred commit fault' USING ERRCODE='23514'; END $$");f.sql("CREATE CONSTRAINT TRIGGER reject_custom_commit AFTER INSERT ON role_definition_owner_operation DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION reject_custom_commit()");var input=f.activation();try{assertEquals(503,f.post(client,f.activatePath(candidate),input).statusCode());}finally{f.sql("DROP TRIGGER reject_custom_commit ON role_definition_owner_operation");f.sql("DROP FUNCTION reject_custom_commit()");}absent(input.get("operationId"));assertEquals(201,f.post(client,f.activatePath(candidate),input).statusCode());return null;
        });
    }
    @Test void preparationFailureDoesNotLeaveOrphanDefinitionOrCandidate()throws Exception{
        var actor=f.rows.identity(IamIntegrationFixtures.Persona.PRA);f.http.withSignedInClient(actor,(client,ctx)->{f.delegate(actor);long definitions=f.count("SELECT count(*) FROM identity_role_definition"),candidates=f.count("SELECT count(*) FROM identity_role_candidate");var input=f.proposal();f.sql("CREATE FUNCTION suppress_custom() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END $$");f.sql("CREATE TRIGGER suppress_custom BEFORE INSERT ON audit_evidence FOR EACH ROW EXECUTE FUNCTION suppress_custom()");try{assertEquals(503,f.post(client,"/api/v1/administration/roles/candidates",input).statusCode());}finally{f.sql("DROP TRIGGER suppress_custom ON audit_evidence");f.sql("DROP FUNCTION suppress_custom()");}absent(input.get("operationId"));assertEquals(definitions,f.count("SELECT count(*) FROM identity_role_definition"));assertEquals(candidates,f.count("SELECT count(*) FROM identity_role_candidate"));return null;});
    }
    @Test void initialAuthorityRefusalRetainsOnlySecurityEvidenceAndRequiredAuditFailureRollsItBack()throws Exception{
        var actor=f.rows.identity(IamIntegrationFixtures.Persona.ORDINARY);f.http.withSignedInClient(actor,(client,ctx)->{var input=f.proposal();assertEquals(403,f.post(client,"/api/v1/administration/roles/candidates",input).statusCode());securityRefusal(input.get("operationId"));
            f.sql("CREATE FUNCTION suppress_custom() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END $$");f.sql("CREATE TRIGGER suppress_custom BEFORE INSERT ON audit_evidence FOR EACH ROW EXECUTE FUNCTION suppress_custom()");var failed=f.proposal();try{assertEquals(503,f.post(client,"/api/v1/administration/roles/candidates",failed).statusCode());}finally{f.sql("DROP TRIGGER suppress_custom ON audit_evidence");f.sql("DROP FUNCTION suppress_custom()");}absent(failed.get("operationId"));return null;});
    }
    @Test void sameOperationConcurrentAndLostResponseResolutionRetainOneResultChangedIntentRefuses()throws Exception{
        var actor=f.rows.identity(IamIntegrationFixtures.Persona.PRA);f.http.withSignedInClient(actor,(client,ctx)->{f.delegate(actor);var candidate=f.prepare(client);var input=f.activation();var replies=concurrent(()->f.post(client,f.activatePath(candidate),input),()->f.post(client,f.activatePath(candidate),input));assertEquals(List.of(201,201),replies.stream().map(HttpResponse::statusCode).toList());assertEquals(f.json.readTree(replies.get(0).body()),f.json.readTree(replies.get(1).body()));assertEquals(f.json.readTree(replies.get(0).body()),f.json.readTree(f.post(client,f.activatePath(candidate),input).body()));var changed=new HashMap<>(input);changed.put("reason","Changed intent");assertEquals(409,f.post(client,f.activatePath(candidate),changed).statusCode());assertEquals(1,f.count("SELECT count(*) FROM audit_evidence WHERE operation_id='"+input.get("operationId")+"'"));assertEquals(2,f.count("SELECT count(*) FROM role_definition_authorization_evidence WHERE operation_id='"+input.get("operationId")+"'"));return null;});
    }
    @Test void differentActorCannotResolveAnotherActorsResultAndConcurrentDifferentIdsSealOnce()throws Exception{
        var first=f.rows.identity(IamIntegrationFixtures.Persona.PRA);var second=f.rows.identity(IamIntegrationFixtures.Persona.PRA);f.http.withSignedInClient(first,(client,ctx)->f.http.withSignedInClient(second,(other,ctx2)->{f.delegate(first);f.delegate(second);var candidate=f.prepare(client);var input=f.activation();var replies=concurrent(()->f.post(client,f.activatePath(candidate),input),()->f.post(client,f.activatePath(candidate),f.activation()));assertEquals(List.of(201,409),replies.stream().map(HttpResponse::statusCode).sorted().toList());var own=f.proposal();var prepared=f.post(client,"/api/v1/administration/roles/candidates",own);assertEquals(201,prepared.statusCode());var denied=f.post(other,"/api/v1/administration/roles/candidates",own);assertEquals(403,denied.statusCode());assertFalse(denied.body().contains("custom-"));assertEquals(1,f.count("SELECT count(*) FROM identity_role_version_profile WHERE definition_id='"+candidate.path("definitionId").asString()+"'"));return null;}));
    }
    @Test void revokedDelegateWaitingForSecurityLockCannotActivate()throws Exception{
        var actor=f.rows.identity(IamIntegrationFixtures.Persona.PRA);f.http.withSignedInClient(actor,(client,ctx)->{var authority=f.delegate(actor);var candidate=f.prepare(client);var input=f.activation();try(var c=f.rows.migrator();var q=c.createStatement();var pool=Executors.newSingleThreadExecutor()){c.setAutoCommit(false);q.execute("SELECT pg_advisory_xact_lock(73003002)");q.execute("UPDATE identity_role_assignment SET revoked_at=CURRENT_TIMESTAMP WHERE assignment_id='"+authority+"'");var wait=pool.submit(()->f.post(client,f.activatePath(candidate),input));boolean witnessed=false;for(int i=0;i<100&&!witnessed;i++){witnessed=f.count("SELECT count(*) FROM pg_locks WHERE locktype='advisory' AND classid=0 AND objid=73003002 AND NOT granted")>0;if(!witnessed)Thread.sleep(20);}assertTrue(witnessed);c.commit();assertEquals(403,wait.get(15,TimeUnit.SECONDS).statusCode());}assertEquals(0,f.count("SELECT count(*) FROM identity_role_version_profile WHERE definition_id='"+candidate.path("definitionId").asString()+"'"));securityRefusal(input.get("operationId"));return null;});
    }
    void securityRefusal(Object op)throws Exception{for(var t:List.of("access_policy_owner_outcome","role_definition_owner_operation"))assertEquals(0,f.count("SELECT count(*) FROM "+t+" WHERE operation_id='"+op+"'"));assertEquals(1,f.count("SELECT count(*) FROM role_definition_authorization_evidence WHERE stage='REQUEST' AND operation_id='"+op+"'"));assertEquals(1,f.count("SELECT count(*) FROM audit_evidence WHERE outcome='REFUSED' AND reason_code='AUTHORITY_REFUSED' AND operation_id='"+op+"'"));}
    void absent(Object op)throws Exception{for(var t:List.of("access_policy_owner_outcome","role_definition_owner_operation","role_definition_authorization_evidence","audit_evidence"))assertEquals(0,f.count("SELECT count(*) FROM "+t+" WHERE operation_id='"+op+"'"));}
    static <T>List<T> concurrent(Callable<T> a,Callable<T> b)throws Exception{try(var pool=Executors.newFixedThreadPool(2)){var latch=new CyclicBarrier(2);var x=pool.submit(()->{latch.await(5,TimeUnit.SECONDS);return a.call();});var y=pool.submit(()->{latch.await(5,TimeUnit.SECONDS);return b.call();});return List.of(x.get(20,TimeUnit.SECONDS),y.get(20,TimeUnit.SECONDS));}}
}
