import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {readFile} from "node:fs/promises";
import {spawnSync} from "node:child_process";
import {createRequire} from "node:module";
import {qualifyBrowser} from "../../apps/web/src/features/iamIntegration/iamIntegration.browser.test.ts";
import {qualifyAccessibility} from "../../apps/web/src/features/iamIntegration/iamIntegration.accessibility.test.ts";
import {qualifyFailure} from "../../apps/web/src/features/iamIntegration/iamIntegration.failure.test.ts";
const [source,manifest,label]=process.argv.slice(2);
assert.match(source??"",/^[0-9a-f]{40}$/);assert.match(manifest??"",/^[0-9a-f]{64}$/);assert.match(label??"",/^(inspection|final)-qualification-[0-9]{2}$/);
const root=`/home/phuclam/idea-iam-ui-20261007-46/run-${label}`,url="https://localhost:18446/",endpoint="/api/v1/administration/access-inspections";
const sha=b=>createHash("sha256").update(b).digest("hex"),ssh=["-i","C:/Users/TD-999/.ssh/idea_ddm_dev_ed25519","-o","BatchMode=yes","-o","StrictHostKeyChecking=yes","-o","ConnectTimeout=8"];
let stage="preflight",browser,fixture,leak=false,callerActor=false;const secrets=[],passed=[];
const pass=name=>{passed.push(name);console.log(`${name}=PASS`);};
async function login(page,user,password){await page.goto(url);await page.getByRole("form",{name:"Đăng nhập",exact:true}).waitFor();await page.locator('[name="username"]').fill(user);await page.locator('[name="password"]').fill(password);const r=page.waitForResponse(r=>new URL(r.url()).pathname==="/api/v1/identity/login"&&r.request().method()==="POST");await page.getByRole("button",{name:"Đăng nhập",exact:true}).click();assert.equal((await r).status(),200);await page.getByTestId("session-actor").waitFor();}
async function open(page){await page.goto(url+"#access");await page.getByRole("form",{name:"Kiểm tra effective access",exact:true}).waitFor();}
async function inspect(page,target,permission,status=200){await page.getByLabel("Target ActorId",{exact:true}).fill(target);await page.getByLabel("Permission code",{exact:true}).fill(permission);const r=page.waitForResponse(r=>new URL(r.url()).pathname===endpoint&&r.request().method()==="POST");await page.getByRole("button",{name:"Đọc effective access",exact:true}).click();const response=await r;assert.equal(response.status(),status);if(status!==200)return;const body=await response.json();await page.getByTestId("inspection-result").waitFor();return body;}
async function lookup(page,id){await page.getByLabel("OperationId",{exact:true}).fill(id);const r=page.waitForResponse(r=>new URL(r.url()).pathname===`/api/v1/administration/operations/${id}`);await page.getByRole("button",{name:"Đọc kết quả operation",exact:true}).click();const response=await r;assert.equal(response.status(),200);const body=await response.json();await page.getByTestId("operation-resolution").waitFor();return body;}
async function privacy(page){const values=await page.evaluate(()=>({text:document.body.innerText,url:location.href,local:JSON.stringify(localStorage),session:JSON.stringify(sessionStorage),cookie:document.cookie}));for(const secret of secrets)for(const value of Object.values(values))assert.equal(value.includes(secret),false);assert.equal(values.cookie.includes("IDEA_SESSION="),false);assert.equal(values.local,"{}");assert.equal(values.session,"{}");}
try{
  assert.equal(process.version,"v24.19.0");assert.equal(sha(await readFile(process.execPath)),"3602f2bb1a10f2cbab4c36886218a33c1ab3db87290e73b033c46c77147d0237");assert.equal(sha(await readFile("C:/Program Files/Google/Chrome/Application/chrome.exe")),"d3784ffbf1f6109348416064b3e4cd739b06fa61d89a81b262c780df9f32270c");
  const base="C:/Users/TD-999/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/";for(const name of ["playwright","playwright-core"])assert.equal(JSON.parse(await readFile(base+name+"/package.json","utf8")).version,"1.62.1");
  const read=spawnSync("C:/Windows/System32/OpenSSH/ssh.exe",[...ssh,"phuclam@192.168.137.33",`test "$(stat -c '%U:%a' ${root}/fixture.private.json)" = phuclam:600 && cat ${root}/fixture.private.json`],{encoding:"utf8",windowsHide:true,timeout:10000});assert.equal(read.status,0);fixture=JSON.parse(read.stdout);read.stdout="";assert.equal(fixture.source,source);secrets.push(fixture.adminPassword,fixture.memberPassword,fixture.ordinaryPassword);
  const {chromium}=createRequire(import.meta.url)(base+"playwright");browser=await chromium.launch({channel:"chrome",headless:false});assert.equal(browser.version(),"155.0.8059.39");const ctx=await browser.newContext(),ordinaryCtx=await browser.newContext();
  for(const context of [ctx,ordinaryCtx]){context.on("page",p=>p.on("console",m=>{if(secrets.some(s=>m.text().includes(s)))leak=true;}));context.on("request",r=>{if(Object.entries(r.headers()).some(([k,v])=>/^(actorid|x-actor-id)$/i.test(k)||v===fixture.adminActorId))callerActor=true;if(secrets.some(s=>r.url().includes(s)))leak=true;});}
  const page=await ctx.newPage(),ordinary=await ordinaryCtx.newPage();
  stage="all-contributing-paths";await login(page,fixture.adminLogin,fixture.adminPassword);await page.goto(url+"#rbac");await page.getByRole("link",{name:"Kiểm tra quyền thực tế",exact:true}).click();await page.getByRole("form",{name:"Kiểm tra effective access",exact:true}).waitFor();await page.getByLabel("Phạm vi kiểm tra",{exact:true}).selectOption(fixture.projectId);const paths=await inspect(page,fixture.memberActorId,"project.read");assert.equal(paths.rbacResult,"ALLOW");assert.equal(paths.paths.length,2);assert.deepEqual(paths.paths.map(p=>p.assignmentId).sort(),[fixture.directAssignmentId,fixture.groupAssignmentId].sort());assert.equal(paths.paths.filter(p=>p.groupId).length,1);assert.ok(paths.paths.every(p=>p.roleVersion===1&&p.assignedBy&&p.reason));const cookie=(await ctx.cookies(url)).find(c=>c.name==="IDEA_SESSION");assert.ok(cookie&&cookie.secure&&cookie.httpOnly&&cookie.sameSite==="Strict"&&cookie.domain==="localhost");pass("I01_ACTUAL_INSPECTOR_DIRECT_GROUP_EXACT_PROVENANCE");
  await page.getByLabel("Exact ProjectId",{exact:true}).fill(fixture.projectId.toUpperCase());await page.getByRole("button",{name:"Kiểm tra scope Project",exact:true}).click();assert.equal((await inspect(page,fixture.memberActorId.toUpperCase(),"project.read")).rbacResult,"ALLOW");
  stage="owner-gates-not-membership-bypass";const admin=await inspect(page,fixture.adminActorId,"project.admin.read");assert.equal(admin.rbacResult,"ALLOW");assert.equal(admin.projectMembershipEligible,false);assert.equal(admin.ownerBusinessGate,"NOT_EVALUATED");await page.getByText(/Owner business gates: NOT_EVALUATED/).waitFor();pass("I02_RBAC_ALLOW_SEPARATE_FROM_ENGINEERING_MEMBERSHIP_OWNER_GATES");
  stage="independent-history-unsupported";await page.getByLabel("Phạm vi kiểm tra",{exact:true}).selectOption("ORGANIZATION");const audit=await inspect(page,fixture.adminActorId,"audit.read");assert.equal(audit.rbacResult,"UNSUPPORTED");assert.equal(audit.implementationState,"DESIGN");assert.equal(await page.getByRole("button",{name:"History · chưa hỗ trợ",exact:true}).isDisabled(),true);const history=await page.evaluate(async path=>(await fetch(path,{credentials:"same-origin"})).status,`/api/v1/administration/history?organizationId=${fixture.organizationId}`);assert.equal(history,409);pass("I03_INDEPENDENT_HISTORY_NOT_UNLOCKED_BY_RBAC");
  stage="actual-owner-result-read-not-replay";await page.goto(url+"#projects");await page.getByRole("button",{name:"Tạo Project",exact:true}).click();const form=page.getByRole("form",{name:"Tạo Project",exact:true});await form.locator('[name="name"]').fill("Synthetic final Inspector project");await form.locator('[name="reason"]').fill("Synthetic original owner operation for read qualification");const created=page.waitForResponse(r=>new URL(r.url()).pathname==="/api/v1/administration/projects"&&r.request().method()==="POST");await form.getByRole("button",{name:"Tạo Project trên Server",exact:true}).click();const response=await created;assert.equal(response.status(),201);const operationId=JSON.parse(response.request().postData()).operationId;await open(page);const resolved=await lookup(page,operationId);assert.equal(resolved.state,"COMMITTED_ACCEPTED");assert.equal(resolved.actorId,fixture.adminActorId);assert.equal(resolved.owner,"PROJECT");assert.equal((await lookup(page,operationId)).state,"COMMITTED_ACCEPTED");const unknown=await lookup(page,"00000000-0000-4000-8000-000000009999");assert.equal(unknown.state,"UNRESOLVED");pass("I04_ORIGINAL_OWNER_RESULT_AND_UNKNOWN_NONDISCLOSURE_NO_REPLAY");
  assert.equal((await lookup(page,operationId.toUpperCase())).state,"COMMITTED_ACCEPTED");await page.getByLabel("OperationId",{exact:true}).fill("-".repeat(36));await page.getByRole("button",{name:"Đọc kết quả operation",exact:true}).click();assert.equal(await page.getByLabel("OperationId",{exact:true}).evaluate(e=>e.validity.patternMismatch),true);assert.equal(await page.getByTestId("operation-resolution").count(),0);
  stage="lost-read-and-visible-refusal";await page.getByLabel("Target ActorId",{exact:true}).fill(fixture.adminActorId);await page.getByLabel("Permission code",{exact:true}).fill("access.inspect");const loss=await ctx.newCDPSession(page);let attempts=0,lostStatus;
  await loss.send("Fetch.enable",{patterns:[{urlPattern:`*${endpoint}`,requestStage:"Response"}]});loss.on("Fetch.requestPaused",async e=>{attempts++;lostStatus=e.responseStatusCode;await loss.send("Fetch.failRequest",{requestId:e.requestId,errorReason:"Failed"});});await page.getByRole("button",{name:"Đọc effective access",exact:true}).click();await page.getByTestId("inspection-status").filter({hasText:"Không lấy được dữ liệu đọc"}).waitFor();assert.equal(attempts,1);assert.equal(lostStatus,200);assert.equal(await page.getByTestId("inspection-result").count(),0);await loss.send("Fetch.disable");await loss.detach();
  const controlled={};for(const status of [409,503]){await page.route(`**${endpoint}`,route=>route.fulfill({status,body:""}));await inspect(page,fixture.adminActorId,"access.inspect",status);await page.getByTestId("inspection-status").filter({hasText:status===409?"Dữ liệu đã thay đổi":"Không lấy được dữ liệu đọc"}).waitFor();assert.equal(await page.getByTestId("inspection-result").count(),0);controlled[status]=status;await page.unroute(`**${endpoint}`);}
  await page.route(`**${endpoint}`,route=>route.continue({headers:{...route.request().headers(),"x-csrf-token":"invalid-synthetic-csrf"}}));await inspect(page,fixture.adminActorId,"access.inspect",403);await page.getByTestId("inspection-status").filter({hasText:"Server từ chối"}).waitFor();await page.unroute(`**${endpoint}`);await inspect(page,fixture.adminActorId,"access.inspect");pass("I05_READ_LOSS_BAD_CSRF_CONTROLLED_STALE_UNAVAILABLE_FAIL_CLOSED");
  stage="ordinary-no-target-disclosure";await login(ordinary,fixture.ordinaryLogin,fixture.ordinaryPassword);await ordinary.goto(url+"#access");await ordinary.getByText("Chưa có quyền access.inspect được Server xác nhận. Không giả lập effective access.",{exact:true}).waitFor();assert.equal(await ordinary.getByRole("form",{name:"Kiểm tra effective access",exact:true}).count(),0);const ordinaryStatus=await ordinary.evaluate(async input=>{const c=await (await fetch("/api/v1/identity/csrf",{credentials:"same-origin"})).json();return (await fetch(input.path,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json",[c.headerName]:c.token},body:JSON.stringify(input.body)})).status;},{path:endpoint,body:{targetActorId:fixture.adminActorId,permissionCode:"access.inspect",scope:{kind:"ORGANIZATION",organizationId:fixture.organizationId}}});assert.equal(ordinaryStatus,403);pass("I06_ORDINARY_REFUSAL_NO_FAKE_AUTHORITY");
  stage="invalidated-session-and-reload";const logout=await page.evaluate(async()=>{const c=await (await fetch("/api/v1/identity/csrf",{credentials:"same-origin"})).json();return (await fetch("/api/v1/identity/logout",{method:"POST",credentials:"same-origin",headers:{[c.headerName]:c.token}})).status;});assert.equal(logout,204);await inspect(page,fixture.adminActorId,"access.inspect",401);await page.getByRole("form",{name:"Đăng nhập",exact:true}).waitFor();await page.reload();await page.getByRole("form",{name:"Đăng nhập",exact:true}).waitFor();await login(page,fixture.adminLogin,fixture.adminPassword);await open(page);await page.reload();await page.getByRole("form",{name:"Kiểm tra effective access",exact:true}).waitFor();qualifyBrowser({secure:cookie.secure,httpOnly:cookie.httpOnly,sameSite:cookie.sameSite,host:cookie.domain,authenticated:200,invalidated:401,reloaded:true});pass("I07_INVALIDATED_SESSION_FRESH_LOGIN_RELOAD_ORDINARY_AUTH_ONLY");
  stage="cross-screen-keyboard-recovery-privacy";for(const route of ["accounts","projects","custom-role","rbac"]){await page.goto(url+"#"+route);await page.locator(".admin-main").first().waitFor();}
  const trigger=page.getByRole("button",{name:"Thêm phân quyền vai trò",exact:true});await trigger.focus();await trigger.click();const dialog=page.getByRole("dialog");await dialog.waitFor();await page.waitForFunction(()=>document.activeElement?.id==="assignment-wizard-title");const initialFocus=await dialog.evaluate(d=>d.contains(document.activeElement));await page.keyboard.press("Shift+Tab");const trapped=await dialog.evaluate(d=>d.contains(document.activeElement));await page.keyboard.press("Escape");await dialog.waitFor({state:"detached"});const focusRestored=await trigger.evaluate(e=>e===document.activeElement);const visibleFocus=await trigger.evaluate(e=>{const s=getComputedStyle(e);return (s.outlineStyle!=="none"&&parseFloat(s.outlineWidth)>0)||s.boxShadow!=="none";});
  await open(page);await page.setViewportSize({width:780,height:900});await page.getByLabel("Target ActorId",{exact:true}).focus();await page.keyboard.press("Tab");const logicalOrder=await page.getByLabel("Permission code",{exact:true}).evaluate(e=>e===document.activeElement);assert.equal(logicalOrder,true);const noClickableDiv=await page.evaluate(()=>document.querySelectorAll('div[role="button"]').length===0),noOverflow=await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth);await inspect(page,fixture.adminActorId,"access.inspect");const statusHasText=Boolean(await page.getByTestId("inspection-status").textContent());qualifyAccessibility({initialFocus,trapped,escapeClosed:await dialog.count()===0,focusRestored,visibleFocus,noClickableDiv,noOverflow,statusHasText});
  await privacy(page);await privacy(ordinary);qualifyFailure({ordinary:ordinaryStatus,csrf:403,stale:controlled[409],unavailable:controlled[503],lostReadAttempts:attempts,lostReadStatus:lostStatus,history,unknownState:unknown.state,leaked:leak,clientAuthoritativeActor:callerActor});await page.getByRole("button",{name:"Đăng xuất",exact:true}).click();await page.getByRole("form",{name:"Đăng nhập",exact:true}).waitFor();pass("I08_ORIGINAL_SHELL_FOCUS_ESCAPE_RESPONSIVE_AND_PRIVATE_STATE");
  await ctx.close();await ordinaryCtx.close();console.log(`INSPECTION_BROWSER=PASS;SOURCE=${source};CASES=${passed.length};HTTPS=NORMAL_TRUST;CHROME=155.0.8059.39;RETAINED_SECRETS=0`);
}catch(error){const safeValue=v=>typeof v==="number"||typeof v==="boolean"?String(v):"REDACTED";const named=/^ACCESSIBILITY_BOUNDARY_FAILED:(?:initialFocus|trapped|escapeClosed|focusRestored|visibleFocus|noClickableDiv|noOverflow|statusHasText)(?:,(?:initialFocus|trapped|escapeClosed|focusRestored|visibleFocus|noClickableDiv|noOverflow|statusHasText))*$/.test(error?.message??"")?error.message:null;const code=named??(error instanceof assert.AssertionError?"ASSERTION":error?.name==="TimeoutError"?"TIMEOUT":/strict mode violation/.test(error?.message??"")?"AMBIGUOUS_LOCATOR":/certificate|self.signed/i.test(error?.message??"")?"TRUST":"REDACTED");console.error(`INSPECTION_BROWSER=FAIL;STAGE=${stage};ERROR=${code};ACTUAL=${safeValue(error?.actual)};EXPECTED=${safeValue(error?.expected)};NO_PRIVATE_DIAGNOSTICS_RETAINED=true`);process.exitCode=1;}
finally{if(browser)await browser.close();secrets.length=0;fixture=undefined;}
