#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# STAGES: Issue #26 synthetic preview setup. Library above unchanged.
TOTAL_STAGES=3
root=/home/phuclam/.local/share/idea/dev-preview-26
here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
java=/opt/idea/tools/jdk-25.0.4.1+1/bin/java
expected=48fe98659db3c075b771a90fd0f4fc61f79a01c01cc941114db9a5299a685bde
[[ $(id -un) == phuclam && -t 0 && -t 1 ]] || { echo 'Run as phuclam in an interactive SSH terminal, not sudo bash.'; exit 2; }
[[ -d $root && ! -L $root && $(stat -c '%a:%U' "$root") == 700:phuclam ]] || { echo 'Private preview directory prerequisite missing'; exit 2; }
[[ $(sha256sum "$root/server.jar" | cut -d ' ' -f 1) == "$expected" ]] || { echo 'Retained JAR hash mismatch'; exit 2; }
[[ ! -e $root/provisioned ]] || { echo 'SETUP_ALREADY_COMPLETE; use launcher Start'; exit 0; }
umask 077
exec 9>"$root/setup.lock"
flock -n 9 || { echo 'Another setup is running'; exit 2; }
ENV_FILE="$root/operator.env"
banner "IDEA synthetic Backend preview (no company data)"
stage "1. Create the new isolated database"
say "Only database idea_ddm_preview_20261001_26 is targeted."
say "No role password, existing database, Vault or Ubuntu service is changed."
if [[ ! -f $root/database-created ]]; then
  confirm "Create this NEW synthetic database? sudo password stays in this terminal." || exit 2
  sudo -u postgres psql --no-psqlrc --set=ON_ERROR_STOP=on < "$here/create-preview.sql"
  touch "$root/database-created"
else
  note "This setup already created its database; continuing its unfinished setup."
fi
stage "2. PostgreSQL credentials and packaged V1-V7"
say "Enter the existing PostgreSQL role passwords, not your SSH/Windows password."
say "They are stored only in this user's private preview directory (mode 600)."
ask_secret PREVIEW_APP_INPUT "Password of idea_ddm_app:"
ask_secret PREVIEW_MIGRATOR_INPUT "Password of idea_ddm_migrator:"
[[ -n $PREVIEW_APP_INPUT && -n $PREVIEW_MIGRATOR_INPUT ]] || { echo 'Empty PostgreSQL credentials refused'; exit 2; }
write_env IDEA_DATABASE_HOST 127.0.0.1
write_env IDEA_DATABASE_PORT 5432
write_env IDEA_DATABASE_NAME idea_ddm_preview_20261001_26
write_env IDEA_DATABASE_SCHEMA public
write_env IDEA_DATABASE_APP_USER idea_ddm_app
write_env IDEA_DATABASE_MIGRATION_USER idea_ddm_migrator
printf -v quoted '%q' "$PREVIEW_APP_INPUT"; write_env IDEA_DATABASE_APP_PASSWORD "$quoted"
printf -v quoted '%q' "$PREVIEW_MIGRATOR_INPUT"; write_env IDEA_DATABASE_MIGRATION_PASSWORD "$quoted"
unset PREVIEW_APP_INPUT PREVIEW_MIGRATOR_INPUT quoted
chmod 600 "$ENV_FILE"
set -a; source "$ENV_FILE"; set +a
"$java" -Dloader.main=com.idea.ddm.migration.DatabaseMigrationCommand -cp "$root/server.jar" org.springframework.boot.loader.launch.PropertiesLauncher
"$java" -Dloader.main=com.idea.ddm.migration.DatabaseMigrationCommand -cp "$root/server.jar" org.springframework.boot.loader.launch.PropertiesLauncher
ENV_FILE="$root/runtime.env"
write_env IDEA_DATABASE_HOST 127.0.0.1
write_env IDEA_DATABASE_PORT 5432
write_env IDEA_DATABASE_NAME idea_ddm_preview_20261001_26
write_env IDEA_DATABASE_SCHEMA public
write_env IDEA_DATABASE_APP_USER idea_ddm_app
printf -v quoted '%q' "$IDEA_DATABASE_APP_PASSWORD"; write_env IDEA_DATABASE_APP_PASSWORD "$quoted"
unset quoted IDEA_DATABASE_MIGRATION_PASSWORD IDEA_DATABASE_MIGRATION_USER
write_env IDEA_SERVER_TLS_ENABLED true
write_env IDEA_SERVER_TLS_KEY_STORE /home/phuclam/idea-f03b-web-tls-739db09df96d4d97ac69fce17bc32fae/server.p12
write_env IDEA_SERVER_TLS_KEY_STORE_TYPE PKCS12
write_env IDEA_SERVER_TLS_KEY_ALIAS idea-t043
chmod 600 "$ENV_FILE"
stage "3. Create a SYNTHETIC IDEA custodian (console only)"
say "The next four prompts should receive these synthetic values, in order:"
step "Organization UUID: 00000000-0000-4000-8000-000000000026"
step "Organization name: IDEA Preview 26"
step "Custodian display name: Preview Developer"
step "Login: preview.dev"
say "Then choose a NEW test password and confirm it (not echoed). Remember it for Web login."
say "Do not use company, SSH or PostgreSQL passwords. Do not paste passwords into chat."
confirm "Continue to the official console bootstrap?" || exit 2
bash "$here/bootstrap-preview.sh"
finish
echo 'IDEA_PREVIEW_SETUP_COMPLETE'
echo 'NEXT=Windows IDEA-Dev.cmd Start; HTTPS https://localhost:18444/'
