import {useEffect,useRef,useState,type FormEvent} from "react";
import {createIamClient,customRoleCeiling,type AdministrationContext,type AssignmentScope,type BoundedPage,type IamResult,type PermissionView,type ProjectView,type RoleCandidate,type RoleValidation,type RoleView} from "../../api/iamClient";
import {outcomeMessage} from "../iamIntegration/IamStatus";
const client=createIamClient();
type Pending={operationId:string;run():Promise<IamResult<unknown>>;confirm(value:unknown):Promise<void>|void};
export function roleProposalTarget(base:string,roles:RoleView[],name:string):{definitionId:string;baseVersionId:string}|{name:string}|null{
  const selected=roles.find(r=>r.roleVersionId===base);
  return selected?{definitionId:selected.definitionId,baseVersionId:selected.roleVersionId}:{name:name.trim()};
}
/** Candidate staging and immutable activation; every assignment stays independently governed. */
export function CustomRoleEditor({context,onInvalidated}:{context:AdministrationContext;onInvalidated():void}){
  const [scope,setScope]=useState<AssignmentScope>({kind:"ORGANIZATION",organizationId:context.organizationId});
  const [projects,setProjects]=useState<BoundedPage<ProjectView>|null>(null),[projectId,setProjectId]=useState("");
  const [roles,setRoles]=useState<BoundedPage<RoleView>|null>(null),[permissions,setPermissions]=useState<PermissionView[]|null>(null);
  const [base,setBase]=useState(""),[name,setName]=useState(""),[codes,setCodes]=useState<string[]>([]),[scopes,setScopes]=useState<string[]>(["PROJECT"]),[principals,setPrincipals]=useState<string[]>(["ACTOR"]);
  const [reason,setReason]=useState(""),[activationReason,setActivationReason]=useState(""),[confirmed,setConfirmed]=useState(false);
  const [candidate,setCandidate]=useState<RoleCandidate|null>(null),[validation,setValidation]=useState<RoleValidation|null>(null),[active,setActive]=useState<RoleView|null>(null);
  const [message,setMessage]=useState(""),[busy,setBusy]=useState(false),[pending,setPending]=useState<Pending|null>(null),[operation,setOperation]=useState("");
  const alive=useRef(true),epoch=useRef(0),heading=useRef<HTMLHeadingElement>(null),status=useRef<HTMLParagraphElement>(null);
  const locked=busy||pending!==null,canPrepare=context.actions.includes("role.definition.prepare"),canActivate=context.actions.includes("role.definition.activate");
  function failed(r:IamResult<unknown>){setMessage(r.kind==="unresolved"?"Chưa xác định kết quả. Không tạo OperationId mới; chỉ resolve lại đúng intent đã gửi.":outcomeMessage(r));if(r.kind==="refused"&&r.status===401){setCandidate(null);setValidation(null);setRoles(null);setPermissions(null);onInvalidated();}}
  async function load(s=scope,offset=0){const request=++epoch.current;setRoles(null);setPermissions(null);const [r,p]=await Promise.all([client.loadRoles(s,offset),client.loadPermissions(s)]);if(!alive.current||request!==epoch.current)return;if(r.kind==="confirmed")setRoles(r.value);else failed(r);if(p.kind==="confirmed"&&!p.value.hasMore)setPermissions(p.value.items);else if(p.kind==="confirmed")setMessage("Catalogue Permission chưa đầy đủ; chưa thể prepare.");else failed(p);}
  useEffect(()=>{alive.current=true;heading.current?.focus();void load();if(context.actions.includes("project.admin.read"))void client.loadProjects().then(r=>{if(alive.current){if(r.kind==="confirmed")setProjects(r.value);else failed(r);}});return()=>{alive.current=false;epoch.current++;};},[context.actorId,context.organizationId]);
  function edit(){setCandidate(null);setValidation(null);setActive(null);setConfirmed(false);setMessage("");}
  async function changeScope(value:string){if(locked)return;const s:AssignmentScope=value==="ORGANIZATION"?{kind:"ORGANIZATION",organizationId:context.organizationId}:{kind:"PROJECT",organizationId:context.organizationId,projectId:value};edit();setBase("");setScope(s);if(s.kind==="PROJECT")setScopes(["PROJECT"]);await load(s);}
  function toggle(values:string[],value:string){return values.includes(value)?values.filter(v=>v!==value):[...values,value].sort();}
  function selectBase(value:string){edit();setBase(value);const r=roles?.items.find(r=>r.roleVersionId===value);if(r){setName(r.displayName);setCodes(r.permissions.map(p=>p.code));setScopes(r.scopeKinds);setPrincipals(r.principalKinds);}else{setName("");setCodes([]);}}
  async function execute(intent:Pending){if(busy)return;setBusy(true);setOperation(intent.operationId);setMessage("Server kiểm current authority, scope và version trước commit…");try{const r=await intent.run();if(!alive.current)return;if(r.kind==="confirmed"){setPending(null);await intent.confirm(r.value);}else{setPending(r.kind==="unresolved"?intent:null);setValidation(null);setConfirmed(false);failed(r);}}finally{if(alive.current){setBusy(false);requestAnimationFrame(()=>status.current?.focus());}}}
  function prepare(e:FormEvent){e.preventDefault();if(locked||!canPrepare||!codes.length||!scopes.length||!principals.length)return;const target=roleProposalTarget(base,roles?.items??[],name);if(!target){setMessage("Exact base không còn trong trang catalogue. Chọn lại version; không tự chuyển thành definition mới.");return;}const input={operationId:crypto.randomUUID(),scope,...target,permissionCodes:[...codes],support:{scopeKinds:[...scopes],principalKinds:[...principals]},reason:reason.trim()};void execute({operationId:input.operationId,run:()=>client.prepareRole(input),confirm:value=>{setCandidate(value as RoleCandidate);setValidation(null);setActive(null);setMessage("Server đã lưu candidate; chưa active và chưa cấp assignment.");}});}
  async function validate(){if(locked||!candidate)return;setBusy(true);setValidation(null);setConfirmed(false);const c=candidate;try{const r=await client.validateRole(c.candidateId,{scope:c.managementScope,expectedVersion:c.version});if(!alive.current)return;if(r.kind==="confirmed"&&r.value.candidate.contentDigest===c.contentDigest&&r.value.candidate.candidateId===c.candidateId){setValidation(r.value);setCandidate(r.value.candidate);setMessage("Validation đạt tại thời điểm đọc. Activation vẫn kiểm lại tại commit.");}else failed(r.kind==="confirmed"?{kind:"unresolved"}:r);}finally{if(alive.current){setBusy(false);requestAnimationFrame(()=>status.current?.focus());}}}
  function activate(e:FormEvent){e.preventDefault();if(locked||!canActivate||!validation||!confirmed)return;const c=validation.candidate,input={operationId:crypto.randomUUID(),scope:c.managementScope,expectedVersion:c.version,baseVersionId:c.baseVersionId,reason:activationReason.trim()};void execute({operationId:input.operationId,run:()=>client.activateRole(c.candidateId,input),confirm:async value=>{const r=value as RoleView;setActive(r);setValidation(null);setConfirmed(false);setCandidate({...c,state:"ACTIVATED",activatedVersionId:r.roleVersionId,version:c.version+1});await load(c.managementScope);if(alive.current)setMessage("Server đã active version immutable mới. Assignment cũ không đổi; version mới cần cấp/thay thế riêng.");}});}
  const custom=roles?.items.filter(r=>!r.builtIn&&r.managementScope?.kind===scope.kind&&(scope.kind==="ORGANIZATION"||r.managementScope.kind==="PROJECT"&&r.managementScope.projectId===scope.projectId))??[];
  return <div className="account-layout custom-role-layout"><section className="admin-main" aria-label="Custom Role">
    <div className="admin-main-head"><div><div className="admin-crumbs">Quản trị hệ thống &gt; RBAC &gt; Custom Role</div><h1 className="admin-main-title" ref={heading} tabIndex={-1}>Quản lý Custom Role</h1><p className="admin-main-desc">Candidate → validate → immutable version. Không sửa built-in hoặc tự chuyển assignment.</p></div><a className="admin-btn" href="#rbac">← Về phân quyền RBAC</a></div>
    <div className="admin-toolbar"><label>Management scope<select aria-label="Management scope" disabled={locked} value={scope.kind==="ORGANIZATION"?"ORGANIZATION":scope.projectId} onChange={e=>void changeScope(e.target.value)}><option value="ORGANIZATION">Organization · {context.organizationName}</option>{projects?.items.map(p=><option key={p.projectId} value={p.projectId}>Project · {p.name}</option>)}{scope.kind==="PROJECT"&&!projects?.items.some(p=>p.projectId===scope.projectId)&&<option value={scope.projectId}>Project · {scope.projectId}</option>}</select></label><button type="button" disabled={locked} onClick={()=>{setValidation(null);setConfirmed(false);void load();}}>Tải lại catalogue</button></div>
    {!context.actions.includes("project.admin.read")&&<form onSubmit={e=>{e.preventDefault();if(/^[0-9a-f-]{36}$/i.test(projectId))void changeScope(projectId);}}><label>Exact ProjectId được quản lý<input aria-label="Exact ProjectId được quản lý" disabled={locked} value={projectId} onChange={e=>setProjectId(e.target.value)} /></label><button disabled={locked} type="submit">Mở management scope Project</button><p className="hint">Không suy quyền browse Project từ PRA; Server kiểm exact scope.</p></form>}
    {projects?.hasMore&&<button disabled={locked} type="button" onClick={()=>void client.loadProjects("",projects.offset+projects.limit).then(r=>{if(alive.current){if(r.kind==="confirmed")setProjects(r.value);else failed(r);}})}>Trang Project tiếp theo</button>}
    <p ref={status} tabIndex={-1} role="status" aria-live="polite" data-testid="custom-role-status" className="status-message">{message}</p>{operation&&<p className="hint">Operation: <code>{operation}</code></p>}{pending&&<div role="alert"><p>Kết quả chưa rõ. Intent chỉ giữ trong RAM đến khi rời màn hình; không tự gửi lại.</p><button disabled={busy} type="button" onClick={()=>void execute(pending)}>Resolve lại cùng OperationId</button></div>}
    {!canPrepare&&<p>Chưa có authority prepare được Server xác nhận. Candidate không thể tự cấp quyền.</p>}
    {canPrepare&&roles&&permissions&&<form className="form-card" aria-label="Chuẩn bị Custom Role" onSubmit={prepare}><fieldset disabled={locked}><legend>1 · Chuẩn bị candidate</legend>
      <label>Definition / exact base<select aria-label="Definition / exact base" value={base} onChange={e=>selectBase(e.target.value)}><option value="">Tạo Custom Role mới</option>{custom.map(r=><option key={r.roleVersionId} value={r.roleVersionId} disabled={!r.selectable}>{r.roleCode}@{r.version} — {r.displayName}</option>)}</select></label>
      <label>Tên hiển thị<input aria-label="Tên hiển thị Custom Role" value={name} readOnly={!!base} required maxLength={200} onChange={e=>{edit();setName(e.target.value);}} /></label>
      <fieldset><legend>Supported Permission ceiling</legend>{permissions.filter(p=>(customRoleCeiling as readonly string[]).includes(p.code)).map(p=><label className="check-label" key={p.code}><input type="checkbox" aria-label={p.code} checked={codes.includes(p.code)} disabled={p.implementationState!=="IMPLEMENTED"} onChange={()=>{edit();setCodes(toggle(codes,p.code));}} /><span><code>{p.code}</code> · {p.implementationState}<small className="hint"> · {p.scopeKinds.join(" / ")} · {p.principalKinds.join(" / ")}</small></span></label>)}</fieldset>
      <fieldset><legend>Assignment scope support</legend>{["ORGANIZATION","PROJECT"].map(s=><label className="check-label" key={s}><input type="checkbox" aria-label={`Scope support ${s}`} disabled={scope.kind==="PROJECT"&&s==="ORGANIZATION"} checked={scopes.includes(s)} onChange={()=>{edit();setScopes(toggle(scopes,s));}} />{s}</label>)}</fieldset>
      <fieldset><legend>Principal support</legend>{["ACTOR","PROJECT_GROUP"].map(p=><label className="check-label" key={p}><input type="checkbox" aria-label={`Principal support ${p}`} checked={principals.includes(p)} onChange={()=>{edit();setPrincipals(toggle(principals,p));}} />{p}</label>)}</fieldset>
      <p className="hint">`project.read` có thể hỗ trợ Project Group. Read/inspection quản trị chỉ ACTOR; support phải là tập con profile Permission. Server quyết định.</p>
      <label>Lý do chuẩn bị<input name="reason" aria-label="Lý do chuẩn bị" required maxLength={500} value={reason} onChange={e=>{edit();setReason(e.target.value);}} /></label><button className="primary" type="submit" disabled={!codes.length||!scopes.length||!principals.length}>Lưu candidate mới</button>
    </fieldset></form>}
    {roles&&<><h2>Exact immutable versions</h2><div className="admin-table-container"><table className="admin-data-table" aria-label="Custom Role versions"><thead><tr><th>Code / version</th><th>Permission</th><th>Principal / scope</th></tr></thead><tbody>{custom.map(r=><tr key={r.roleVersionId}><td><code>{r.roleCode}@{r.version}</code><code>{r.roleVersionId}</code></td><td>{r.permissions.map(p=><div key={p.code}>{p.code}</div>)}</td><td>{r.principalKinds.join(", ")} / {r.scopeKinds.join(", ")}</td></tr>)}</tbody></table></div><div className="actions"><button type="button" disabled={locked||roles.offset===0} onClick={()=>void load(scope,Math.max(0,roles.offset-roles.limit))}>Trang version trước</button><button type="button" disabled={locked||!roles.hasMore} onClick={()=>void load(scope,roles.offset+roles.limit)}>Trang version tiếp theo</button></div></>}
  </section><aside className="admin-inspector" aria-label="Candidate và activation"><div className="admin-inspector-body"><h2>2 · Validate / activate</h2>{!candidate?<p>Chưa có candidate được Server xác nhận.</p>:<>
    <dl><dt>Candidate</dt><dd><code data-testid="candidate-id">{candidate.candidateId}</code></dd><dt>Exact Role</dt><dd><code>{candidate.roleCode}@{candidate.proposedRoleVersion}</code></dd><dt>Management scope</dt><dd>{candidate.managementScope.kind} · <code>{candidate.managementScope.kind==="PROJECT"?candidate.managementScope.projectId:candidate.managementScope.organizationId}</code></dd><dt>State / candidate version</dt><dd>{candidate.state} / {candidate.version}</dd><dt>Principal / scope support</dt><dd>{candidate.support.principalKinds.join(", ")} / {candidate.support.scopeKinds.join(", ")}</dd><dt>Content digest</dt><dd><code>{candidate.contentDigest}</code></dd></dl>
    <div aria-label="Permission diff"><p>Added: {candidate.difference.added.join(", ")||"—"}</p><p>Removed: {candidate.difference.removed.join(", ")||"—"}</p><p>Unchanged: {candidate.difference.unchanged.join(", ")||"—"}</p></div>
    {candidate.state==="CANDIDATE"&&<button type="button" disabled={locked} onClick={()=>void validate()}>Validate candidate</button>}
    {validation&&<form aria-label="Xác nhận activation" onSubmit={activate}><fieldset disabled={locked||!canActivate}><ul>{validation.consequences.map(c=><li key={c}>{c}</li>)}</ul><label>Lý do activation<input required maxLength={500} aria-label="Lý do activation" value={activationReason} onChange={e=>setActivationReason(e.target.value)} /></label><label className="check-label"><input type="checkbox" aria-label="Xác nhận không đổi assignment cũ" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} />Tôi hiểu assignment cũ không đổi.</label><button className="primary" type="submit" disabled={!confirmed}>Activate immutable version</button></fieldset></form>}
    {active&&<p role="status">Activated: <code>{active.roleCode}@{active.version}</code>. Cấp/thay thế assignment riêng tại RBAC.</p>}
  </>}<p className="hint">Đổi proposal tạo candidate mới. Không sửa Role built-in, không tạo Permission mới, không có policy script.</p></div></aside></div>;
}
